### ISSUE TITLE
Thanks! ✨

### ISSUE THREAD

**Issue by wuhhh** [mandrasch/ddev-laravel-vite#2]
I just came to say thank you for this - and to ponder, why are there so few people using DDEV & Laravel 🤔

**Comment by mandrasch** [comment]
hey @wuhhh! 

thanks for the positive feedback and letting me know that it was useful. 😎  👍 

There are some laravel users in the [DDEV discord](https://discord.com/invite/hCZFfAMc5k). But I guess the low DDEV usage within laravel community is mainly because Laravel offers laravel valet (now herd) for local development as well as sail as own docker solution? So tutorials will point you to these solutions?

CraftCMS, TYPO3, etc. will point you to DDEV in their official tutorials / getting started guide.
